openapi: 3.0.3
info:
  title: Mathesar API
  version: 1.0.0
paths:
  /api/db/v0/data_files/:
    get:
      operationId: data_files_list
      parameters:
      - in: query
        name: database
        schema:
          type: array
          items:
            type: string
        description: Multiple values may be separated by commas.
        explode: false
        style: form
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - in: query
        name: name
        schema:
          type: array
          items:
            type: string
        description: Multiple values may be separated by commas.
        explode: false
        style: form
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - in: query
        name: sort_by
        schema:
          type: array
          items:
            type: string
            enum:
            - -id
            - -name
            - id
            - name
        description: |-
          Sort By

          * `id` - Id
          * `-id` - Id (descending)
          * `name` - Name
          * `-name` - Name (descending)
        explode: false
        style: form
      tags:
      - data_files
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedDataFileList'
          description: ''
    post:
      operationId: data_files_create
      tags:
      - data_files
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataFile'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/DataFile'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DataFile'
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataFile'
          description: ''
  /api/db/v0/data_files/{id}/:
    get:
      operationId: data_files_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this data file.
        required: true
      tags:
      - data_files
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataFile'
          description: ''
    patch:
      operationId: data_files_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this data file.
        required: true
      tags:
      - data_files
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedDataFile'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedDataFile'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedDataFile'
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataFile'
          description: ''
  /api/db/v0/databases/:
    get:
      operationId: databases_list
      parameters:
      - in: query
        name: deleted
        schema:
          type: boolean
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - in: query
        name: sort_by
        schema:
          type: array
          items:
            type: string
            enum:
            - -id
            - -name
            - id
            - name
        description: |-
          Sort By

          * `id` - Id
          * `-id` - Id (descending)
          * `name` - Name
          * `-name` - Name (descending)
        explode: false
        style: form
      tags:
      - databases
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedDatabaseList'
          description: ''
  /api/db/v0/databases/{id}/:
    get:
      operationId: databases_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this database.
        required: true
      tags:
      - databases
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Database'
          description: ''
  /api/db/v0/databases/{id}/functions/:
    get:
      operationId: databases_functions_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this database.
        required: true
      tags:
      - databases
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Database'
          description: ''
  /api/db/v0/databases/{id}/types/:
    get:
      operationId: databases_types_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this database.
        required: true
      tags:
      - databases
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Database'
          description: ''
  /api/db/v0/schemas/:
    get:
      operationId: schemas_list
      parameters:
      - in: query
        name: database
        schema:
          type: array
          items:
            type: string
        description: Multiple values may be separated by commas.
        explode: false
        style: form
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - in: query
        name: name
        schema:
          type: array
          items:
            type: string
        description: Multiple values may be separated by commas.
        explode: false
        style: form
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - in: query
        name: sort_by
        schema:
          type: array
          items:
            type: string
            enum:
            - -id
            - -name
            - id
            - name
        description: |-
          Sort By

          * `id` - Id
          * `-id` - Id (descending)
          * `name` - Name
          * `-name` - Name (descending)
        explode: false
        style: form
      tags:
      - schemas
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedSchemaList'
          description: ''
    post:
      operationId: schemas_create
      tags:
      - schemas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Schema'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Schema'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Schema'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schema'
          description: ''
  /api/db/v0/schemas/{id}/:
    get:
      operationId: schemas_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this schema.
        required: true
      tags:
      - schemas
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schema'
          description: ''
    patch:
      operationId: schemas_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this schema.
        required: true
      tags:
      - schemas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedSchema'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedSchema'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedSchema'
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schema'
          description: ''
    delete:
      operationId: schemas_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this schema.
        required: true
      tags:
      - schemas
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /api/db/v0/schemas/{id}/dependents/:
    get:
      operationId: schemas_dependents_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this schema.
        required: true
      tags:
      - schemas
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schema'
          description: ''
components:
  schemas:
    DataFile:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        file:
          type: string
          format: uri
        table_imported_to:
          type: integer
          readOnly: true
        user:
          type: integer
          readOnly: true
        header:
          type: boolean
          default: true
        delimiter:
          type: string
          maxLength: 1
        escapechar:
          type: string
          maxLength: 1
        quotechar:
          type: string
          maxLength: 1
        paste:
          type: string
        url:
          type: string
          format: uri
        created_from:
          enum:
          - FILE
          - PASTE
          - URL
          type: string
          description: |-
            * `FILE` - File
            * `PASTE` - Paste
            * `URL` - Url
          readOnly: true
        max_level:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
      required:
      - created_from
      - id
      - table_imported_to
      - user
    Database:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          readOnly: true
        deleted:
          type: boolean
          readOnly: true
        supported_types_url:
          type: string
          readOnly: true
      required:
      - deleted
      - id
      - name
      - supported_types_url
    PaginatedDataFileList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/DataFile'
    PaginatedDatabaseList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/Database'
    PaginatedSchemaList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/Schema'
    PatchedDataFile:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        file:
          type: string
          format: uri
        table_imported_to:
          type: integer
          readOnly: true
        user:
          type: integer
          readOnly: true
        header:
          type: boolean
          default: true
        delimiter:
          type: string
          maxLength: 1
        escapechar:
          type: string
          maxLength: 1
        quotechar:
          type: string
          maxLength: 1
        paste:
          type: string
        url:
          type: string
          format: uri
        created_from:
          enum:
          - FILE
          - PASTE
          - URL
          type: string
          description: |-
            * `FILE` - File
            * `PASTE` - Paste
            * `URL` - Url
          readOnly: true
        max_level:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
    PatchedSchema:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        database:
          type: string
        has_dependents:
          type: string
          readOnly: true
        description:
          type: string
          nullable: true
        num_tables:
          type: string
          readOnly: true
        num_queries:
          type: string
          readOnly: true
    Schema:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        database:
          type: string
        has_dependents:
          type: string
          readOnly: true
        description:
          type: string
          nullable: true
        num_tables:
          type: string
          readOnly: true
        num_queries:
          type: string
          readOnly: true
      required:
      - database
      - has_dependents
      - id
      - name
      - num_queries
      - num_tables
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
