name: Run Python tests
on: 
  push:
    paths:
      - '*.py'
      - 'mathesar/**'
      - 'db/**'
  pull_request:
    paths:
      - '*.py'
      - 'mathesar/**'
      - 'db/**'


jobs:
  tests:
    runs-on: ubuntu-latest
    # We only want to run on external PRs, since internal PRs are covered by "push"
    # This prevents this from running twice on internal PRs
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@v2

      - name: Copy env file
        run: cp .env.example .env

      # The code is checked out under uid 1001 - reset this to 1000 for the
      # container to run tests successfully
      - name: Fix permissions
        run: sudo chown -R 1000:1000 .

      - name: Build the stack
        run: docker compose -f docker-compose.yml -f docker-compose.dev.yml up --build -d test-service

      - name: Run tests with pytest
        run: docker exec mathesar_service_test ./run_pytest.sh
